'''
Created on Sep 11, 2012

@author: reza
'''
#--------------------------------------------------------------------

NUM_TRIALS = 10

NUM_STATS_GAMES = 10000

COLLECT_STATS = False
SAVE_STATS = False

PRINT_GAME_DETAIL = False
PRINT_GAME_RESULTS = False
#PRINT_GAME_DETAIL = True
#PRINT_GAME_RESULTS = True

ALTERNATE_SEATS = True
#ALTERNATE_SEATS = False
USE_SEEDS = ALTERNATE_SEATS

CHOOSE_ROLL_P = 1.0

GENERATE_GRAPH_REPORT_EVERY_N_STATES = 1000
RECORD_GRAPH = False

EVAL_OPPONENT_RANDOM = 'EVAL_OPPONENT_RANDOM'
EVAL_OPPONENT_Q_LEARNING = 'EVAL_OPPONENT_Q_LEARNING'
EVAL_OPPONENT = EVAL_OPPONENT_Q_LEARNING

#--------------------------------------------------------------------

#TD_NUM_ITERATIONS = 200
#TD_NUM_TRAINING_GAMES = 16 # 64
#TD_NUM_EVAL_GAMES = 1024
TD_NUM_ITERATIONS = 300
TD_NUM_TRAINING_GAMES = 16 # 64
TD_NUM_EVAL_GAMES = 512

TD_GAMMA = 1.0
TD_ALPHA = 1.0
TD_EPSILON = 0.05
TD_LAMBDA = 0.7

TD_TRAIN_EPOCHS = 1
TD_LEARNING_RATE = 0.1

TD_USE_ALPHA_ANNEALING = False

#--------------------------------------------------------------------

Q_GAMMA = 1.0
Q_ALPHA = 0.1
Q_EPSILON = 0.05
Q_LAMBDA = 0.90

Q_LEARNING_USE_ALPHA_ANNEALING = True
Q_LEARNING_MIN_ALPHA = 0.05

Q_LEARNING_NUM_ITERATIONS = 1000 * 1024
Q_LEARNING_NUM_FINAL_EVAL = 1024

Q_LEARNING_TRAIN_AGAINST_SELF = False

Q_LEARNING_SAVE_TRIAL_DATA = True

Q_LEARNING_SAVE_TABLES = True
Q_LEARNING_SAVE_STATE_VALUES_IN_GRAPH = True

#--------------------------------------------------------------------

HC_NUM_GENERATIONS = 500
HC_NUM_CHALLENGE_GAMES = 8
HC_CHALLENGER_NEEDS_TO_WIN = 7
HC_NUM_EVAL_GAMES = 1024
HC_EVALUATE_EVERY_N_GENERATIONS = 10

HC_RATIO_KEEP_CHAMPION_WEIGHTS = 0.95
HC_MUTATE_WEIGHT_SIGMA = 0.22 # 0.05

#--------------------------------------------------------------------

GAMESET_PROGRESS_REPORT_EVERY_N_GAMES = Q_LEARNING_NUM_ITERATIONS / 1000
GAMESET_RECENT_WINNERS_LIST_SIZE = 3000
GAMESET_PROGRESS_REPORT_USE_GZIP = False

